chatroom/urls.py
from django.conf.urls import url
from . import views

app_name = "chatroom"

urlpatterns = [
    url("^$" , views.inbox , name = "inbox"),
    url("^updatemessage/" , views.updatemessage , name = "updatemessage"),
    url("^check_new_message/" , views.check_new_message , name = "newmessage"),
    url("^adminpanel/$" , views.adminpanel , name = "adminpanel"),
    url("^(?P<chat_user>[\d]+)/$" , views.chatrm , name = "chatroom"),
    url("^updatechats/$" , views.updatechats , name = "updatechats"),
    url("^delete/(?P<chtid>[\d]+)/(?P<chat_user>[\d]+)/$" , views.deletechat , name = "delete")
]

devcodes/urls.py
from django.contrib import admin
# from django.urls import path
# from django.conf.urls import handler404
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url('master/', admin.site.urls),
    url("^$" , include("home.urls")),
    url("login/" , include("login.urls")),
    url("signup/" , include("signup.urls")),
    url("profile/" , include("uprofile.urls")),
    url("questions/" , include("questions.urls")),
    url("peers/" , include("peer.urls")),
    url("chatroom/" , include("chatroom.urls")),
        # url(r'^oauth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)


handler404 = views.handler404

handler500 = views.handler500

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home")
    ]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

peer/urls.py
from django.conf.urls import url
from . import views

app_name = "peers"

urlpatterns = [
    url("^$" , views.peers , name = "peers"),
    url("locatepeers/" , views.locatepeers , name="locatepeers")
]

questions/urls.py
from django.conf.urls import url
from . import views
app_name = "questions"

urlpatterns = [
    url("^$" , views.questionsview , name = "questions"),
    url("^feedback/$" , views.feed , name = "feedback"),
    url("^updatelikes/$" , views.updatelikes , name = "updatelikes"),
    url("^myquestions/$" , views.myquestions , name = "myquestions"),
    url("^updateanswers/(?P<Qid>[\d]+)/$" , views.update_answers , name = "updateanswers"),
    url("^answers/(?P<Qid>[\d]+)/$" , views.answersview , name = "answers"),
    url("^updatequestions/$" , views.askquestionsview , name = "askquestions"),
]

uprofile/urls.py
from django.conf.urls import url
from . import views
app_name = "profile"

urlpatterns = [
    url("^$" , views.profileview , name = "profile"),
    url("^update/" , views.update_profile , name = "update"),
    url( "^changepassword/$" , views.changepassword , name = "changepassword"),
]

questions/models.py
from django.db import models
from signup.models import Signup
from cloudinary.models import CloudinaryField


# The questions to answer
class Questions(models.Model):
    qid = models.AutoField(primary_key = True , serialize = True)
    quid = models.ForeignKey(Signup , related_name = "question_asker" , on_delete = models.CASCADE)
    question = models.CharField(max_length = 1025)
    time_posted = models.DateTimeField(auto_now_add = True)
    language = models.CharField(max_length = 15 , default = "Python")
    # qphoto = models.FileField("image" , default = "")

    class Meta:
        db_table = "Questions"


# The answers class
class Answers(models.Model):
    aid = models.AutoField(primary_key = True , serialize = True)
    auid = models.ForeignKey(Signup , related_name = "question_answerer" , on_delete = models.CASCADE)
    question_to_answer = models.ForeignKey(Questions , related_name = "question_to_answer" , on_delete = models.CASCADE)
    answer = models.CharField(max_length = 255)
    time_posted = models.DateTimeField(auto_now_add = True)

    class Meta:
        db_table = "Answers"


class QuestionLike(models.Model):
    lid = models.AutoField(primary_key = True , serialize = True)
    Qid = models.ForeignKey(Questions , related_name = "question_liked" , on_delete = models.CASCADE)
    luid = models.ForeignKey(Signup , related_name = "Qliker" , on_delete = models.CASCADE)


    class Meta:
        db_table = "likes"

questions/forms.py
from django.forms import ModelForm , Textarea , TextInput
from .models import Answers

class anserform(ModelForm):
    class Meta:
        model = Answers
        fields = ("answer",)

        widgets = {
        "answer":Textarea(attrs = {"cols":40 , "rows":3 , "Placeholder":"Your answer" , "id":"large" , "maxlength":1025}),
        }


        labels = {
        "answer":""
        }

questions/views.py
from django.shortcuts import render , redirect
from signup.models import Signup
from .forms import anserform
from django.db.models import Count
from .models import Questions , Answers , QuestionLike as qlike
from chatroom.models import ChatModel as chtb
from chatroom.models import FeedBack as fd
from django.http import JsonResponse , HttpResponse
from itertools import chain

def custom_userquestions(userinfo):
    try:
        custom_q_questions = Questions.objects.all().annotate(no_of_answers = Count("question_to_answer")).order_by("-time_posted").filter(language__icontains = userinfo.hobby)
        the_rest_question = Questions.objects.all().annotate(no_of_answers = Count("question_to_answer")).order_by("-time_posted").exclude(language__icontains = userinfo.hobby)
        all_questions = chain(custom_q_questions , the_rest_question)
    except Exception as e:
        all_questions = Questions.objects.all().annotate(no_of_answers = Count("question_to_answer")).order_by("-time_posted")
        return all_questions
    else:
        return all_questions


def questionsview(request):
    try:
        userdetails = Signup.objects.get(username = request.session["username"])
        all_questions = custom_userquestions(userdetails)
        newmessage = chtb.objects.filter(r2uid_id =  userdetails.uid, bell_seen = False).count()
        userlog = True
    except Exception as e:
        userlog = False
        request.session["redirect"] = "/questions/"
        return redirect("/login/")
        return render(request , "questions/questions.html" , context = {"Questions":all_questions , "userlog":userlog})
    else:
        return render(request , "questions/questions.html" , context = {"Questions":all_questions , "mydetails":userdetails , "newmessage":newmessage , "userlog":userlog})

def myquestions(request):
    try:
        userdetails = Signup.objects.get(username = request.session["username"])
        newmessage = chtb.objects.filter(r2uid_id =  userdetails.uid, bell_seen = False).count()
        userlog = True
    except Exception as e:
        userlog = False
        request.session["redirect"] = "/questions/myquestions/"
        return redirect("/login/")

    else:
        all_questions = Questions.objects.filter(quid_id = userdetails.uid).annotate(no_of_answers = Count("question_to_answer")).order_by("-time_posted")
        return render(request , "questions/personal.html" , context = {"Questions":all_questions , "mydetails":userdetails , "newmessage":newmessage , "userlog":userlog})


def answersview(request , Qid):
    answers_form = anserform()

    allanswers = Answers.objects.filter(question_to_answer_id = Qid)
    question_info = Questions.objects.get(qid = Qid)

    try:
        userdetails = Signup.objects.get(username = request.session["username"])
        userlog = True
    except Exception as e:
        userlog = False
        return render(request , "questions/answers.html" , context = {"userdetails":"userdetails" , "answers_form":answers_form , "Qid":Qid , "allanswers":allanswers , "question_info":question_info , "newmessage":0})

    else:
        newmessage = chtb.objects.filter(r2uid_id =  userdetails.uid, bell_seen = False).count()
        return render(request , "questions/answers.html" , context = {"userdetails":userdetails , "answers_form":answers_form , "Qid":Qid , "allanswers":allanswers , "question_info":question_info , "newmessage":newmessage , "userlog":userlog})

def askquestionsview(request):
    if request.method == "POST":
        try:
            userdetails = Signup.objects.get(username = request.session["username"])
            questionlang = request.POST["language"]
            question = request.POST["question"]
            # try:
            #     qphoto = request.FILES["qphoto"]
            # except Exception as e:
            #     pass
            # else:
            #     pass
        except Exception as e:
            request.session["redirect"] = "/questions/updatequestions/"
            return redirect("/login/")

        else:
            Questions.objects.create(quid_id = userdetails.uid, question = question , language = questionlang)
            return redirect("/questions/")
    else:
        return redirect("/questions/")


def update_answers(request , Qid):

    if request.method == "POST":
        try:
            userdetails = Signup.objects.get(username = request.session['username'])
            answerquery = request.POST["answer"]

        except Exception as e:
            request.session["redirect"] = "/questions/updateanswers/{}/".format(Qid)
            return redirect("/login/")

        else:
            Answers.objects.create(auid_id = userdetails.uid , question_to_answer_id = Qid , answer = answerquery)
            return redirect("/questions/answers/{}/".format(Qid))

    else:
        return redirect("/questions/answers/{}/".format(Qid))

# check if the user has liked or not
def checklikes(qid , uid):
    try:
        qdata = [value.luid_id for value in qlike.objects.filter(Qid_id = qid)]
    except Exception as e:
        return False
    else:
        if uid in qdata:
            return True
        else:
            return False

# update likes
def updatelikes(request):
    try:
        userdetails = Signup.objects.get(username = request.session['username'])
    except Exception as e:
        is_logged = False
        liked = "question not liked"
    else:
        Qid = request.POST["qid"]
        if not checklikes(Qid , userdetails.uid):
            qlike.objects.create(Qid_id = Qid , luid_id = userdetails.uid)
        is_logged = True
        liked = "question liked"
    data = {"liked":liked,"is_logged":is_logged , "counter":Questions.objects.get(qid = Qid).question_liked.count()}
    return JsonResponse(data)


def feed(request):
    user_mail = request.POST["email"]
    feed = request.POST["feedback"]
    fd.objects.create(feedback_sender = user_mail, feedback = feed)
    return JsonResponse({"feedback":True})

questions/templates/questions/personal.html
{% load timemod %}
{% load static %}
{% load cloudinary %}
{% load like %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>DevCodes | Questions </title>
    <link rel="stylesheet" href="{% static 'questions/questions.css' %}">

    <link rel="stylesheet" href="{% static 'home/icon.css' %}">
    <link rel="stylesheet" href="{% static 'questions/personal.css' %}">
    <link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">

  </head>
  <body>
  <div class="nav-bar">

  <!-- Home icon Beginning -->

  <div class="full-icon" id="full">
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
</div>

<div class="no-padding" id="ex">
    <div class="forward-slash"></div>
    <div class="backward-slash"></div>
</div>

<div class="icon-links" id="iLinks">
  <a href="{% url 'home:home' %}" class="Plinks">Home</a>
<a href="{% url 'peers:peers' %}" class="Plinks">Peers</a>
<a href="{% url 'questions:questions' %}" class="Plinks">Questions
 <i class="fa fa-caret-down"></i></a>
<a href="{% url 'questions:myquestions' %}" class="Plinks-in">My Questions</a>
<a href="{% url 'chatroom:inbox' %}" class="Plinks">Inbox <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
     </a>
<a href="{% url 'profile:profile' %}" class="Plinks"> Edit profile </a>
<a href="{% url 'login:logout' %}" class="Plinks">  Log out </a>
</div>

<!-- Ending of icon -->

    <div class="links">
      <a href="{% url 'home:home' %}">Home</a> |
      <a href="{% url 'peers:peers' %}">Peers</a> |
      <a href="{% url 'questions:questions' %}">Questions</a> |
      <a href="{% url 'chatroom:inbox' %}">Inbox</a>
      <a href="{% url 'chatroom:inbox' %}">
        <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
      </a>
      </div>
      <div class="logoN">
        <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width:100px; height:50px;">
      </div>
      <div class="user-profile">
        <a> <i class="fa fa-bell">{{notifs}}</i> </a>
           {% cloudinary mydetails.profilepic.url className="myimg" alt=mydetails.username title=mydetails.username height=200 width=100 %}
    </div>
</div>

  <div class="page-title" id="upPart">My Questions page</div>
  <div class="main-window column">
        <div class="person-holder">
    {% for question in Questions %}

    <div class="oneQuestion">
          <div class="question-container">
            <div class="user-details-first-row">

              {{mydetails.username}}  @
              {{question.time_posted | timemodifier}}
            </div>
            <div class="question-content">
              <div class="question-text personal">{{question.question}}</div>
            <div class="languages-tagged">
              {{question.language}}
              </div>
            </div>
            <div class="reply-section">
             <div class="like">

               {% if mydetails.uid|likey:question %}
                 <div class="like">
                   <img src="{% static 'home/images/svgimages/coloredlove.svg' %}" alt="like" id="Love" style="width: 20px;
                   margin: 5px;
                   height: 20px; cursor: pointer;
                   animation: bigUp .9s 0s ease-out forwards;">
                   <span id="question{{question.qid}}" style="margin-right:20px;">{{question.question_liked.count}}</span>
                 </div>
               {% else %}
                   <div class="like">
                     <img src="{% static 'home/images/svgimages/emptylove.svg' %}" alt="like" id="emptyLove" onclick="updatemonster({{question.qid}});"
                     style="width:20px;height: 20px;margin: 5px;cursor: pointer;">
                     <img src="{% static 'home/images/svgimages/coloredlove.svg' %}" class="colored" alt="like" id="Love" style="width: 20px;margin: 5px;height: 20px;cursor: pointer;animation: bigUp .9s 0s ease-out forwards;">
                     <span id="question{{question.qid}}" style="margin-right:20px;">{{question.question_liked.count}}</span>
                   </div>
               {% endif %}
<!--{{question.no_of_answers}} -->
             </div>
             <div class="message">
             <img src="{% static 'questions/images/message.svg' %}" alt="message icon">
             {{question.no_of_answers}}
             </div>
             <div class="Click">
            <a href="{% url 'questions:answers' question.qid %}"> Click to view replies</a>
             </div>
            </div>
          </div>
        </div>

        </div>
    {% endfor %}
  </div>

  <a href="#upPart"><img src="{% static 'questions/images/up.svg' %}" alt="up_key" class="up-icon"  id="up">
  </a>
<script type="text/javascript">
 // home icon
 const full = document.getElementById('full');
        const ex = document.getElementById('ex');
        const iLinks = document.getElementById('iLinks');

        full.addEventListener('click',function(){
            // full.classList.add('removeIcon');
            full.style.display = 'none';
            // ex.classList.add('showIcon');
            ex.style.display = 'flex';
            iLinks.style.display = 'flex';
        });
        ex.addEventListener('click',function(){
            // full.classList.remove('removeIcon');
            full.style.display = 'flex';
            // ex.classList.remove('showIcon');
            ex.style.display = 'none';
            iLinks.style.display = 'none';
        });
        // end of home icon
  var up=document.getElementById('up');
  window.onscroll=function(){
  var scrollPos=window.pageYOffset;
  if(scrollPos<100){
      up.classList.add('hide');
  }
  else{
      up.classList.remove('hide');
  }
  }

  $(".likebtn").click(function(){
    this.attr("disabled" , true);
    try {
      var xml = new XMLHttpRequest();
    } catch (e) {
      var xml = new XActiveObject();
    } finally {
      xml.onreadystatechange = function() {
        if (this.readyState==4 && this.status==200) {
          alert("Question liked");
        }
      }
      var csid = $("input[type='hidden']").text();
      xml.open("POST" , "{% url 'questions:updatelikes' %}" , true);
      xml.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
      xml.setRequestHeader("X-CSRFToken" , csid);
      xml.send("qid="+qid);
    }
  });
  function updatemonster(qid) {
    document.getElementById("question"+qid.toString()).disabled = true;
    $("#question"+qid.toString()).attr("disabled" , true);
    try {
        var xmlhttp = new XMLHttpRequest();
    } catch (e) {
      var xmlhttp = new ActiveXObject();
    }
    finally {
      xmlhttp.open("POST" , "{% url 'questions:updatelikes' %}" , true);
      xmlhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
      xmlhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
      xmlhttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
          var data = JSON.parse(this.responseText)
          if (data.is_logged) {
            document.getElementById("question"+qid.toString()).innerHTML = data.counter;
          } else {
            $(location).attr("href" , "{% url 'login:login' %}")
          }
        }
      }
      xmlhttp.send("qid=" + qid);
    }
  }
  $(document).ready(function(){
    function checknewmessage(){
      try {
        var xmlhttp = new XMLHttpRequest();
      } catch (e) {
        var xmlhttp = new ActiveXObject();
      } finally {
        xmlhttp.onreadystatechange = function(){
          if (this.readyState ==4 && this.static==200) {
            var elemenets = document.getElementsByClassName('newmessage');
            for (var i = 0; i < elemenets.length; i++) {
              elemenets[i].innerHTML = this.responseText
            }
          }
        }
        xmlhttp.open("POST" , "{% url 'chatroom:newmessage' %}" , true);
        xmlhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
        xmlhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
        xmlhttp.send();
      }
    }
    setInterval(function(){
      checknewmessage();
    } , 3000);
  });
</script>
</body>
</html>