chatroom/urls.py
from django.conf.urls import url
from . import views

app_name = "chatroom"

urlpatterns = [
    url("^$" , views.inbox , name = "inbox"),
    url("^updatemessage/" , views.updatemessage , name = "updatemessage"),
    url("^check_new_message/" , views.check_new_message , name = "newmessage"),
    url("^adminpanel/$" , views.adminpanel , name = "adminpanel"),
    url("^(?P<chat_user>[\d]+)/$" , views.chatrm , name = "chatroom"),
    url("^updatechats/$" , views.updatechats , name = "updatechats"),
    url("^delete/(?P<chtid>[\d]+)/(?P<chat_user>[\d]+)/$" , views.deletechat , name = "delete")
]

devcodes/urls.py
from django.contrib import admin
# from django.urls import path
# from django.conf.urls import handler404
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url('master/', admin.site.urls),
    url("^$" , include("home.urls")),
    url("login/" , include("login.urls")),
    url("signup/" , include("signup.urls")),
    url("profile/" , include("uprofile.urls")),
    url("questions/" , include("questions.urls")),
    url("peers/" , include("peer.urls")),
    url("chatroom/" , include("chatroom.urls")),
        # url(r'^oauth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)


handler404 = views.handler404

handler500 = views.handler500

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home")
    ]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

peer/urls.py
from django.conf.urls import url
from . import views

app_name = "peers"

urlpatterns = [
    url("^$" , views.peers , name = "peers"),
    url("locatepeers/" , views.locatepeers , name="locatepeers")
]

questions/urls.py
from django.conf.urls import url
from . import views
app_name = "questions"

urlpatterns = [
    url("^$" , views.questionsview , name = "questions"),
    url("^feedback/$" , views.feed , name = "feedback"),
    url("^updatelikes/$" , views.updatelikes , name = "updatelikes"),
    url("^myquestions/$" , views.myquestions , name = "myquestions"),
    url("^updateanswers/(?P<Qid>[\d]+)/$" , views.update_answers , name = "updateanswers"),
    url("^answers/(?P<Qid>[\d]+)/$" , views.answersview , name = "answers"),
    url("^updatequestions/$" , views.askquestionsview , name = "askquestions"),
]

uprofile/urls.py
from django.conf.urls import url
from . import views
app_name = "profile"

urlpatterns = [
    url("^$" , views.profileview , name = "profile"),
    url("^update/" , views.update_profile , name = "update"),
    url( "^changepassword/$" , views.changepassword , name = "changepassword"),
]

uprofile/models.py
from django.db import models

# Create your models here.

uprofile/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from chatroom.models import ChatModel as chtb
from django.contrib.auth.hashers import make_password
from signup.models import Signup as sp
import json
def profileview(request):
    if request.method == "GET":
        try:
            mydetails = sp.objects.get(username = request.session['username'])
            newmessage = chtb.objects.filter(r2uid_id =  mydetails.uid, bell_seen = False).count()
        except Exception as e:
            request.session["redirect"] = "/profile/"
            return redirect("/login/")
        else:
            return render(request , "uprofile/uprofile.html" , context = {"mydetails":mydetails , "newmessage":newmessage})

def update_profile(request):
    if request.method == "POST":
        try:
            edit_user_details = sp.objects.get(username = request.session['username'])
            try:
                edit_user_details.profilepic=request.FILES["profile"]
            except Exception as e:
                print(f"{e}\n\n\n\n\n")
            edit_user_details.email = request.POST["email"]
            edit_user_details.username = request.POST["username"]
            edit_user_details.hobby = request.POST["language"].title()
            edit_user_details.save()
            request.session["username"] = request.POST["username"]
        except Exception as e:
            return redirect("/profile/")
        else:
            return redirect("/profile/")
    else:
        return redirect("/profile/")

def changepassword(request):
    logger = False
    try:
        userinfo = sp.objects.get(username = request.session["username"])
    except Exception as e:
        return redirect("/login/")
    else:
        newpass = request.POST["password"]
        confirm = request.POST["confirmpassword"]
        if newpass ==confirm:
            userinfo.password = make_password(newpass)
            userinfo.save()
            password_status = "Password changed sucessfully."
            logger = True
        else:
            password_status = "Pasword not changed. Please try again"
            logger = False

        logger = json.dumps({"logger":True,"password_status":password_status})
        return HttpResponse(logger , content_type = "application/json")

uprofile/templates/uprofile/uprofile.html
{% load static %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>DevCodes | profile</title>
    <link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
    <link rel="stylesheet" href="{% static 'uprofile/uprofile.css' %}">
    <link rel="stylesheet" href="{% static 'home/spinner.css' %}">
    <link rel="stylesheet" href="{% static 'home/icon.css' %}">
  </head>
  <body>
<!-- Begining of spinner -->
<div class="loader-wrapper" id="ld">
  <span class="loader"><span class="loader-inner"></span></span>
      </div>
      <!-- End of spinner -->
     <!-- new nav-bar -->
     <div class="nav-bar">
  <!-- Home icon Beginning -->
  <div class="full-icon" id="full">
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
</div>
<div class="no-padding" id="ex">
    <div class="forward-slash"></div>
    <div class="backward-slash"></div>
</div>
<div class="icon-links" id="iLinks">
  <a href="{% url 'home:home' %}" class="Plinks">Home</a>
<a href="{% url 'peers:peers' %}" class="Plinks">Peers</a>
{% if mydetails.is_admin %}
<a href="{% url 'chatroom:adminpanel' %}" class="Plinks">Admin</a>
{% else %}
{% endif %}
<a href="{% url 'questions:questions' %}" class="Plinks">Questions
 <i class="fa fa-caret-down"></i></a>
<a href="{% url 'questions:myquestions' %}" class="Plinks-in">My Questions</a>
<a href="{% url 'chatroom:inbox' %}" class="Plinks">Inbox <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
     </a>
<a href="{% url 'profile:profile' %}" class="Plinks"> Edit profile </a>
<a href="{% url 'login:logout' %}" class="Plinks">  Log out </a>
</div>
<!-- Ending of icon -->
      <div class="links">
        <a href="{% url 'home:home' %}">Home</a> |
        <a href="{% url 'peers:peers' %}">Peers</a> |
        {% if mydetails.is_admin %}
        <a href="{% url 'chatroom:adminpanel' %}">Admin</a>
        {% else %}

        {% endif %}
          <!-- dropdowm for questions -->
        <div class="dropdown">
       <div class="dropbtn"> <a href="{% url 'questions:questions' %}">Questions<i class="fa fa-caret-down"></i></a>  </div>
        <div class="dropdown-content">   <a href="{% url 'questions:myquestions' %}">My Questions</a>  </div>
     </div>

        |
        <a href="{% url 'chatroom:inbox' %}">Inbox
          <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
        </a>
        </div>
        <div class="logoN" id="upPart">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width:100px; height:50px;">
        </div>
        <div class="user-profile">
          <a> <i class="fa fa-bell">{{notifs}}</i> </a>
             {% cloudinary mydetails.profilepic.url className="myimg" height=200 width=100 alt=mydetails.username title=mydetails.username %}
             <div class="user-dropdown">
               <a href="{% url 'login:logout' %}">
                 Log out
               </a>
             </div>
      </div>
  </div>
      <div class="main-container">

      <div class="main-details">
        <!-- profile pic -->
          {% cloudinary mydetails.profilepic.url className="myimg" height=200 width=100 alt=mydetails.username title=mydetails.username %}
          <!-- update form -->
          <form class="" action="{% url 'profile:update' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
          <fieldset>
            <div class="info">
               <div class="Your"> Your details</div>
                  <div class="sect">
                  <label class="labels">Username</label>
                  <input type="text" class="entry" name="username" value="{{mydetails.username}}" placeholder="Enter username"
                  id="username">
              </div>
               <div class="sect">
                  <label class="labels">Email</label>
                  <input type="text" class="entry" name="email" value="{{mydetails.email}}" placeholder="Enter email" id="email">
               </div>
                <div class="sect">
                  <label class="labels">Language</label>
                  <input type="text" class="entry" name="language" value="{{mydetails.hobby}}" placeholder="Coding languages" id="language">
                </div>
                <div class="sect">
                  <button type="button" class="btn btn-info" name="button" onclick="showpopup();" style="width:max-content;">Change password</button>
                </div>
                <div class="sect">
                  <label class="btn btn-info">
          		        Choose your profile <i class="fa fa-picture-o" aria-hidden="true"></i>
          		        <input type="file" style="display: none;" name="profile" class="entry" id="profile" value="{{mydetails.profilepic}}">
          		    </label>
                </div>
                  <button type="submit" name="submit" class="btn btn-info" onclick="auth()">Update</button>
                </div>
          </fieldset>
          </form>
        </div>
      </div>

      <div class="changepassword" id="changepassword">
      <form class="passwordform" method="post">
        <div class="devcodeslogo">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width: 100px;">
        </div>
        {% csrf_token %}
          <p class="close" id="close" onclick="hidepopup();">&times;</p>
          <div class="onefieldpassword">
            <label class="passwordlabels">New password</label>
            <br>
            <input type="password" name="password" placeholder="New password" required id="pswordfield1" class="pswordfield">
          </div>
          <div class="onefieldpassword">
            <label class="passwordlabels">Confirm password</label>
            <br>
            <input type="password" name="confirmpassword" placeholder="Confirm password" required id="pswordfield2" class="pswordfield">
          </div>
          <div class="onefieldpassword">
            <button type="submit" name="button" class="btn btn-info changepass">Update</button>
          </div>
      </form>
      <div class="password-infor-div">
      </div>
    </div>
  </body>
  <script type="text/javascript">
     // Listen for when everything has loaded
     window.addEventListener("load", removePage, false);
        const loader = document.getElementById('ld');
        function removePage(){
          loader.classList.add('shrink');
        }
         // home icon
  const full = document.getElementById('full');
        const ex = document.getElementById('ex');
        const iLinks = document.getElementById('iLinks');

        full.addEventListener('click',function(){
            full.style.display = 'none';
            ex.style.display = 'flex';
            iLinks.style.display = 'flex';
        });
        ex.addEventListener('click',function(){
            full.style.display = 'flex';
            ex.style.display = 'none';
            iLinks.style.display = 'none';
        });
        // end of home icon
    function auth() {
      var xml = new XMLHttpRequest();

      xml.onreadystatechange = function() {
        if(this.readyState == 4 && this.status == 200){

          // alert(this.responseText);
        }
      }
      xml.open("POST" , "{% url 'profile:update' %}");
      xml.setRequestHeader("X-CSRFToken" , "{{ csrf_token }}");
      xml.send();
    }
      function checknewmessage(){
        try {
          var xmlhttp = new XMLHttpRequest();
        } catch (e) {
          var xmlhttp = new ActiveXObject();
        } finally {
          xmlhttp.onreadystatechange = function(){
            if (this.readyState ==4 && this.static==200) {
              var elemenets = document.getElementsByClassName('newmessage');
              alert(this.responseText)
            }
          }
          xmlhttp.open("POST" , "{% url 'chatroom:newmessage' %}" , true);
          xmlhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
          xmlhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
          xmlhttp.send();
        }
      }
      setInterval(function(){
        checknewmessage();
      } , 3000);

      function showpopup() {
        var pop = document.getElementById("changepassword");
        pop.setAttribute("style" , "display:block;animation: zoomer .4s  ease-out 1;")
      }
      function hidepopup() {
        var popup = document.getElementById("changepassword");
        popup.setAttribute("style" , "display:none;");
      }

      document.querySelector(".changepass").addEventListener("click" , function(e){
        e.preventDefault();
      try {
            var xmlobj = new XMLHttpRequest();
      } catch (e) {
        var xmlobj = new ActiveXObject();
      } finally {
        xmlobj.onreadystatechange = function() {
            if (this.readyState == 4 && this.status==200) {
              document.getElementById("pswordfield1").value = "";
              document.getElementById("pswordfield2").value = "";
                var response = JSON.parse(this.responseText);
                var popel = document.querySelector(".password-infor-div");
                if (response.logger) {
                  document.querySelector(".password-infor-div").value = response.password_status;
                  popel.setAttribute("style" , "display:block");
                  popel.innerHTML = response.password_status;
                  var now = Date.now();
                  while (Date.now()-now< 2000) {
                  }
                  popel.setAttribute("style" , "display:none;");
                  document.querySelector(".changepassword").setAttribute("style" , "display:none;");
                }
                else {
                  popel.innerHTML = response.password_status;
                  popel.setAttribute("style" , "display:block");

                  var now = Date.now();
                  while (Date.now()-now< 2000) {
                  }
                }

            }
        }
        var passwordform = document.querySelector(".passwordform");
        var data = new FormData(passwordform);
          xmlobj.open("POST" , "{% url 'profile:changepassword' %}" , true);
          xmlobj.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
          xmlobj.send(data)
      }
    });
  </script>
</html>