chatroom/urls.py
from django.conf.urls import url
from . import views

app_name = "chatroom"

urlpatterns = [
    url("^$" , views.inbox , name = "inbox"),
    url("^updatemessage/" , views.updatemessage , name = "updatemessage"),
    url("^check_new_message/" , views.check_new_message , name = "newmessage"),
    url("^adminpanel/$" , views.adminpanel , name = "adminpanel"),
    url("^(?P<chat_user>[\d]+)/$" , views.chatrm , name = "chatroom"),
    url("^updatechats/$" , views.updatechats , name = "updatechats"),
    url("^delete/(?P<chtid>[\d]+)/(?P<chat_user>[\d]+)/$" , views.deletechat , name = "delete")
]

devcodes/urls.py
from django.contrib import admin
# from django.urls import path
# from django.conf.urls import handler404
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url('master/', admin.site.urls),
    url("^$" , include("home.urls")),
    url("login/" , include("login.urls")),
    url("signup/" , include("signup.urls")),
    url("profile/" , include("uprofile.urls")),
    url("questions/" , include("questions.urls")),
    url("peers/" , include("peer.urls")),
    url("chatroom/" , include("chatroom.urls")),
        # url(r'^oauth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)


handler404 = views.handler404

handler500 = views.handler500

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home")
    ]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

peer/urls.py
from django.conf.urls import url
from . import views

app_name = "peers"

urlpatterns = [
    url("^$" , views.peers , name = "peers"),
    url("locatepeers/" , views.locatepeers , name="locatepeers")
]

questions/urls.py
from django.conf.urls import url
from . import views
app_name = "questions"

urlpatterns = [
    url("^$" , views.questionsview , name = "questions"),
    url("^feedback/$" , views.feed , name = "feedback"),
    url("^updatelikes/$" , views.updatelikes , name = "updatelikes"),
    url("^myquestions/$" , views.myquestions , name = "myquestions"),
    url("^updateanswers/(?P<Qid>[\d]+)/$" , views.update_answers , name = "updateanswers"),
    url("^answers/(?P<Qid>[\d]+)/$" , views.answersview , name = "answers"),
    url("^updatequestions/$" , views.askquestionsview , name = "askquestions"),
]

uprofile/urls.py
from django.conf.urls import url
from . import views
app_name = "profile"

urlpatterns = [
    url("^$" , views.profileview , name = "profile"),
    url("^update/" , views.update_profile , name = "update"),
    url( "^changepassword/$" , views.changepassword , name = "changepassword"),
]

peer/models.py
from django.db import models

# Create your models here.

peer/views.py
from django.shortcuts import render,redirect
from signup.models import Signup as sp
from chatroom.models import ChatModel as chtb
from django.http import HttpResponse
from itertools import chain

def peers_suggest_per_lang(userinfo):
    try:
        users = sp.objects.exclude(username = userinfo.username).filter(hobby__icontains= userinfo.hobby)
        rest_of_users = sp.objects.exclude(username = userinfo.username).exclude(hobby__icontains = userinfo.hobby)
        users = chain(users , rest_of_users)
    except Exception as e:
        return sp.objects.exclude(username = userinfo.username)
    else:
        return users



def peers(request):
    all_users = sp.objects.all()
    try:
        current_user = sp.objects.get(username = request.session["username"])
        all_users = peers_suggest_per_lang(current_user)
        newmessage = chtb.objects.filter(r2uid_id =  current_user.uid, bell_seen = False).count()

    except Exception as e:
        request.session["redirect"] = "/peers/"
        return redirect("/login/")

    else:
        return render(request , "peers/peers.html" , context = {"users":all_users , "user":current_user , "newmessage":newmessage})


def locatepeers(request):
    try:
        searchterm = request.GET["peer"]
        criteria = request.GET['critrion']
        current_user = sp.objects.get(username = request.session["username"])

    except Exception as e:
        pass

    else:

        if criteria=="username":
            indexed_peers = sp.objects.filter(username__icontains = searchterm).exclude(uid= current_user.uid)
            no_of_results = indexed_peers.count()

        elif criteria=="language":
            indexed_peers = sp.objects.filter(hobby__icontains = searchterm).exclude(uid= current_user.uid)
            no_of_results = indexed_peers.count()

        elif criteria=="location":
            indexed_peers = sp.objects.filter(location__icontains = searchterm).exclude(uid= current_user.uid)
            no_of_results = indexed_peers.count()

        newmessage = chtb.objects.filter(r2uid_id =  current_user.uid, bell_seen = False).count()
        return render(request , "peers/peers.html" , context = {"users":indexed_peers , "user":current_user , "rlsearch":"Related search" ,"small":"search results " , "query":searchterm , "no_of_results" : no_of_results , "newmessage":newmessage})

peer/templates/peers/peers.html
{% load static %}
{% load messagecounter %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>DevCodes | peers</title>
    <link rel="stylesheet" href="{% static 'peers/peers.css' %}">
    <link rel="stylesheet" href="{% static 'home/icon.css' %}">
  </head>
  <body>
    <div class="nav-bar">
  <!-- Home icon Beginning -->
  <div class="full-icon" id="full">
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
    <div class="row">
        <div class="dot"></div>   <div class="line"></div>
    </div>
</div>
<div class="no-padding" id="ex">
    <div class="forward-slash"></div>
    <div class="backward-slash"></div>
</div>
<div class="icon-links" id="iLinks">
  <a href="{% url 'home:home' %}" class="Plinks">Home</a>
<a href="{% url 'peers:peers' %}" class="Plinks">Peers</a>
<a href="{% url 'questions:questions' %}" class="Plinks">Questions
 <i class="fa fa-caret-down"></i></a>
<a href="{% url 'questions:myquestions' %}" class="Plinks-in">My Questions</a>
<a href="{% url 'chatroom:inbox' %}" class="Plinks">Inbox <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
     </a>
<a href="{% url 'profile:profile' %}" class="Plinks"> Edit profile </a>
<a href="{% url 'login:logout' %}" class="Plinks">  Log out </a>
</div>
<!-- Ending of icon -->
      <div class="links">
        <a href="{% url 'home:home' %}">Home</a> |
          <!-- A dropdown for questions -->
        <div class="dropdown">
       <div class="dropbtn"> <a href="{% url 'questions:questions' %}">Questions<i class="fa fa-caret-down"></i></a>  </div>
        <div class="dropdown-content">   <a href="{% url 'questions:myquestions' %}">My Questions</a>  </div>
     </div>
        |
        <a href="{% url 'chatroom:inbox' %}">Inbox</a>
        <a href="{% url 'chatroom:inbox' %}">
          <i class="fa fa-envelope newmessage"> {{newmessage}}</i>
        </a>
        </div>
        <div class="logoN">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width:100px; height:50px;">
        </div>
      <div class="user-profile">
        <a> <i class="fa fa-bell" id="notif1">{{notifs}}</i> </a>
           {% cloudinary user.profilepic.url className="myimg" alt=user.username title=user.username height=200 width=100 %}

           <div class="user-dropdown">
             <a href="{% url 'profile:update' %}">Edit profile</a>
             <a href="{% url 'login:logout' %}">
               Log out
             </a>
           </div>
    </div>
  </div>
    <!-- main page -->
    <div class="main">
      <div class="search" id="upPart">
        <p class="logo">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo">
        </p>
          <form class="search-form" action="{% url 'peers:locatepeers' %}" method="get">
            <input type="search" name="peer" placeholder="Search" required autocomplete="language" value="{{query}}" maxlength="30">
            <button type="submit" name="button" class="btn btn-info">search</button>
            <br>
              <select class="slen" name="critrion" size="1">
                <option value="language" selected>language</option>
                <option value="username">username</option>
                <option value="location">location</option>
              </select>
          </form>
      </div>
          <h5 id="relsearch">{{rlsearch}}</h5>
          <small id="resultscount"> {{small}} {{no_of_results}}</small>
      <hr>
      {% for usr in users %}

      <div class="user-infor">
        <div class="profile">
          {% cloudinary usr.profilepic.url className=usr.username title=usr.username alt=usr.username height=200 width=100 %}
        </div>

        <div class="detail-user">
            <p>
              username - {{usr.username}}
            </p>
            <p class="">
               <i class="fa fa-heart"></i> Language - {{usr.hobby}}
            </p>

            <p class="lower-user">
              <i class="fa fa-map-marker"> {{usr.location}}</i>
            </p>

            <p class="lower-user">
              <a href="{% url 'chatroom:chatroom' usr.uid %}">
                Chat <i class="fa fa-envelope">  {{ usr | messenger:user }}</i>
              </a>
            </p>
        </div>
      </div>

      {% endfor %}
    </div>
    <!-- footer  -->

    <div class="footer">

    </div>
<script>
   // home icon

   const full = document.getElementById('full');
        const ex = document.getElementById('ex');
        const iLinks = document.getElementById('iLinks');

        full.addEventListener('click',function(){
            // full.classList.add('removeIcon');
            full.style.display = 'none';
            // ex.classList.add('showIcon');
            ex.style.display = 'flex';
            iLinks.style.display = 'flex';
        });
        ex.addEventListener('click',function(){
            // full.classList.remove('removeIcon');
            full.style.display = 'flex';
            // ex.classList.remove('showIcon');
            ex.style.display = 'none';
            iLinks.style.display = 'none';
        });

        // end of home icon

        $(document).ready(function(){
          function checknewmessage(){
            try {
              var xmlhttp = new XMLHttpRequest();
            } catch (e) {
              var xmlhttp = new ActiveXObject();
            } finally {
              xmlhttp.onreadystatechange = function(){
                if (this.readyState ==4 && this.static==200) {
                  alert(this.responseText);
                  var elemenets = document.getElementsByClassName('newmessage');
                  for (var i = 0; i < elemenets.length; i++) {
                    elemenets[i].innerHTML = this.responseText
                  }
                }
              }
              xmlhttp.open("POST" , "{% url 'chatroom:newmessage' %}" , true);
              xmlhttp.setRequestHeader("X-CSRFToken" , "{{csrf_token}}");
              xmlhttp.setRequestHeader("Content-Type" , "application/x-www-form-urlencoded");
              xmlhttp.send();
            }
          }
          setInterval(function(){
            checknewmessage();
          } , 3000);
        });
</script>
  </body>
</html>