chatroom/urls.py
from django.conf.urls import url
from . import views

app_name = "chatroom"

urlpatterns = [
    url("^$" , views.inbox , name = "inbox"),
    url("^updatemessage/" , views.updatemessage , name = "updatemessage"),
    url("^check_new_message/" , views.check_new_message , name = "newmessage"),
    url("^adminpanel/$" , views.adminpanel , name = "adminpanel"),
    url("^(?P<chat_user>[\d]+)/$" , views.chatrm , name = "chatroom"),
    url("^updatechats/$" , views.updatechats , name = "updatechats"),
    url("^delete/(?P<chtid>[\d]+)/(?P<chat_user>[\d]+)/$" , views.deletechat , name = "delete")
]

devcodes/urls.py
from django.contrib import admin
# from django.urls import path
# from django.conf.urls import handler404
from django.conf.urls import url , include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url('master/', admin.site.urls),
    url("^$" , include("home.urls")),
    url("login/" , include("login.urls")),
    url("signup/" , include("signup.urls")),
    url("profile/" , include("uprofile.urls")),
    url("questions/" , include("questions.urls")),
    url("peers/" , include("peer.urls")),
    url("chatroom/" , include("chatroom.urls")),
        # url(r'^oauth/', include('social_django.urls', namespace='social')),
]+static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)


handler404 = views.handler404

handler500 = views.handler500

home/urls.py
from django.conf.urls import url
from . import views
app_name = "home"

urlpatterns = [
    url("^$" , views.homeview , name = "home")
    ]

login/urls.py
from . import views
from django.conf.urls import url
app_name = "login"


urlpatterns = [
    url('^$' , views.login , name = 'login'),
    url("^forgot/" , views.forgotcredetials , name = 'forgot'),
    url("^logout/" , views.logout , name = "logout"),
    url("^updatereset/" , views.newcr , name = "newcreds")
]

peer/urls.py
from django.conf.urls import url
from . import views

app_name = "peers"

urlpatterns = [
    url("^$" , views.peers , name = "peers"),
    url("locatepeers/" , views.locatepeers , name="locatepeers")
]

questions/urls.py
from django.conf.urls import url
from . import views
app_name = "questions"

urlpatterns = [
    url("^$" , views.questionsview , name = "questions"),
    url("^feedback/$" , views.feed , name = "feedback"),
    url("^updatelikes/$" , views.updatelikes , name = "updatelikes"),
    url("^myquestions/$" , views.myquestions , name = "myquestions"),
    url("^updateanswers/(?P<Qid>[\d]+)/$" , views.update_answers , name = "updateanswers"),
    url("^answers/(?P<Qid>[\d]+)/$" , views.answersview , name = "answers"),
    url("^updatequestions/$" , views.askquestionsview , name = "askquestions"),
]

uprofile/urls.py
from django.conf.urls import url
from . import views
app_name = "profile"

urlpatterns = [
    url("^$" , views.profileview , name = "profile"),
    url("^update/" , views.update_profile , name = "update"),
    url( "^changepassword/$" , views.changepassword , name = "changepassword"),
]

chatroom/models.py
from django.db import models
from signup.models import Signup as signupobj

class ChatModel(models.Model):
    aid = models.AutoField(primary_key = True , serialize = True)
    text_time = models.DateTimeField(auto_now_add = True)
    text_message = models.CharField(max_length = 1024 , default = "")
    bell_seen = models.BooleanField()
    r1uid = models.ForeignKey(signupobj , related_name = "first_user" , on_delete = models.CASCADE)
    r2uid = models.ForeignKey(signupobj , related_name = "second_user" , on_delete = models.CASCADE)

    class Meta:
        db_table = "Chats"
        get_latest_by = "text_time"

# feedback
class FeedBack(models.Model):
    fid = models.AutoField(primary_key = True ,  serialize = True)
    feedback_sender = models.EmailField(max_length = 40 , default = "Anornymous@gmail.com")
    feedback = models.TextField(max_length = 400 , default = "")
    post_time = models.DateTimeField(auto_now_add = True)

    class Meta:
        db_table = "FeedBack"

chatroom/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse
from signup.models import Signup as signmod
from .models import ChatModel as chatmod , FeedBack as fd
from django.db.models import Q,Max

def db_unique(db_obj , curr_user):
    unique_chat = list()
    for x in db_obj:
        x1 , x2 = x.r1uid_id , x.r2uid_id
        # x1  not me
        if x1 !=curr_user:
            if x1 not in [value.r1uid_id for value in unique_chat] and x1 not in [value.r2uid_id for value in unique_chat]:
                unique_chat.append(x)
        else:
            # x1 is me
            if x2 not in [value.r2uid_id for value in unique_chat] and x2 not in [value.r1uid_id for value in unique_chat]:
                unique_chat.append(x)

    return (unique_chat)


def inbox(request):
    try:
        userdetails = signmod.objects.get(username = request.session["username"])
        newmessage = chatmod.objects.filter(r2uid_id =  userdetails.uid, bell_seen = False).count()
        userlog = True
    except Exception as e:
        userlog = False
        request.session["redirect"] = "/chatroom/"
        return redirect("/login/")

    else:
        all_messages = chatmod.objects.filter(Q(r2uid_id = userdetails.uid) | Q(r1uid_id = userdetails.uid)).order_by("-text_time")

        all_messages = db_unique(all_messages , userdetails.uid)
        return render(request , "chatroom/inbox.html/" , context = {"all_messages":all_messages , "userdetails":userdetails , "newmessage":newmessage , "userlog":userlog})


def chatrm(request , chat_user):
    try:
        userdetails = signmod.objects.get(username = request.session["username"])
        chats = chatmod.objects.filter(Q(r1uid_id = userdetails.uid , r2uid_id = chat_user) | Q(r1uid_id = chat_user , r2uid_id = userdetails.uid)).order_by("text_time")
        check_bell = chatmod.objects.filter(r2uid_id =  userdetails.uid, bell_seen = False)
        check_bell.update(bell_seen = True)
        ch_user = signmod.objects.get(uid = chat_user)
        userlog = True
    except Exception as e:
        userlog = True
        request.session["redirect"] = "/chatroom/{}/".format(chat_user)
        return redirect("/login/")

    else:
        if chat_user==userdetails.uid:
            return redirect("/chatroom/")
        else:
            return render(request , "chatroom/messages.html" , context = {"userdetails":userdetails , "chats":chats , "receiver":ch_user , "userlog":userlog})

# update chats
def updatechats(request):
    if request.method == "POST":
        try:
            receiver = int(request.POST["re"])
            msg = request.POST["msg"]
            id = signmod.objects.get(username = request.session["username"]).uid

        except Exception as e:
            # request.session["redirect"] = "/chatroom/updatechats/"
            receiver = int(request.POST["re"])
            return redirect("/chatroom/{}/#frm".format(receiver))

        else:
            chatmod.objects.create(text_message = msg , r1uid_id = id, r2uid_id = receiver , bell_seen = False)
            return redirect("/chatroom/{}/#frm".format(receiver))
    else:
        pass


def adminpanel(request):
    try:
        userinfo = signmod.objects.get(username = request.session["username"])
    except Exception as e:
        return redirect("/login/")
    else:
        if userinfo.is_admin:
            feeds = fd.objects.all().order_by("-post_time")
            return render(request , "home/admin.html" , context = {"feeds":feeds , "userinfo":userinfo})
        else:
            return redirect("/chatroom/")


def deletechat(request , chtid, chat_user):
    try:
        request.session["username"]
    except Exception as e:
        request.session["redirect"] = "/chatroom/{}/#frm/".format(chat_user)
        return redirect("/login/")
    else:
        chatmod.objects.get(aid = chtid).delete()
        return redirect("/chatroom/{}/#frm/".format(chat_user))


def updatemessage(request):
    try:
        usercreds = signmod.objects.get(username = request.session["username"])
    except Exception as e:
        pass
    else:
        all_messages = chatmod.objects.filter(Q(r2uid_id = usercreds.uid) | Q(r1uid_id = usercreds.uid) , bell_seen = False).order_by("-text_time")
        all_messages = db_unique(all_messages , usercreds.uid)
        all_messages = {"all_messages":all_messages}
    return JsonResponse(all_messages)

def check_new_message(request):
    return 10

chatroom/templates/chatroom/inbox.html
{% load static %}
{% load timemod %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>Dev Code | Inbox </title>
    <link rel="stylesheet" href="{% static 'questions/answers.css' %}">
    <link rel="stylesheet" href="{% static 'home/icon.css' %}">
  </head>
  <body>
    <div class="nav-bar">
      <!-- Home icon Beginning -->
    <div class="full-icon" id="full">
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
  </div>

  <div class="no-padding" id="ex">
      <div class="forward-slash"></div>
      <div class="backward-slash"></div>
  </div>
 <div class="icon-links" id="iLinks">
  <a href="{% url 'home:home' %}" class="Plinks">Home</a>
<a href="{% url 'peers:peers' %}" class="Plinks">Peers</a>
 <a href="{% url 'questions:questions' %}" class="Plinks">Questions
   <i class="fa fa-caret-down"></i></a>
 <a href="{% url 'questions:myquestions' %}" class="Plinks-in">My Questions</a>
 <a href="{% url 'profile:profile' %}" class="Plinks"> Edit profile </a>
 <a href="{% url 'login:logout' %}" class="Plinks">  Log out </a>
 </div>
  <!-- Ending of icon -->
      <div class="links">
        <a href="{% url 'home:home' %}">Home</a> |

        <a href="{% url 'peers:peers' %}">Peers</a> |

          <!-- dropdowm for questions -->
        <div class="dropdown personalize">
       <div class="dropbtn"> <a href="{% url 'questions:questions' %}">Questions<i class="fa fa-caret-down"></i></a>  </div>
        <div class="dropdown-content">   <a href="{% url 'questions:myquestions' %}">My Questions</a>  </div>
     </div>
        </div>
        <div class="logoN">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width:100px; height:50px;">
        </div>
        <div class="user-profile">
          <a> <i class="fa fa-bell">{{notifs}}</i> </a>
             {% cloudinary userdetails.profilepic.url className="myimg" title=userdetails.username alt=userdetails.username height=200 width=100 %}
             <div class="user-dropdown">
               <a href="{% url 'profile:profile' %}">
                 Edit profile
               </a>
               <a href="{% url 'login:logout' %}">
                 Log out
               </a>
             </div>
          </div>
  </div>

    <div class="main">

      <!-- Start of Messages -->
        <h4 id="upPart">Inbox</h4>
        <hr style="width:100px;margin: 0px auto;">
        {% for msg in all_messages %}
            {% if msg.r1uid_id|umodifier:userdetails.uid %}
              <a href="{% url 'chatroom:chatroom' msg.r2uid_id %}" class="mainbox">
                <div class="answers" style="align-items: center;">

                  <div class="profile queryprofile">
                    {% cloudinary msg.r2uid.profilepic.url className="myimg" title=msg.r2uid.username alt=msg.r2uid.username height=200 width=100 %}
                    <p>{{msg.r2uid.username|username_modifier}}</p>
                  </div>

                  <div class="answers-content" style="display: flex; flex-direction: column;justify-content:space-between;">
                    <div class="answers-content">
                      <div class="answers-main-content">
                        {{msg.text_message}}
                      </div>
                      <p class="newmessagec">
                        <a href="{% url 'chatroom:chatroom' msg.r2uid_id %}">
                          open
                        </a>
                      </p>
                    </div>
                    <div class="flexer">
                      <p class="ft">
                        {{msg.r2uid.hobby}}
                      </p>
                      <p class="ft">
                        {{msg.text_time | timemodifier}}
                      </p>

                      {% if msg.bell_seen %}
                      <p class="ft">
                        seen
                      </p>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </a>
            {% else %}
          <a href="{% url 'chatroom:chatroom' msg.r1uid_id %}" class="mainbox">
            <div class="answers" style="align-items: center;">
              <div class="profile queryprofile">
                {% cloudinary msg.r1uid.profilepic.url className="myimg" title=msg.r1uid.username alt=msg.r1uid.username height=200 width=100 %}
                <p>{{msg.r1uid.username|username_modifier}}</p>
              </div>
              <div class="answers-content" style="display: flex; flex-direction: column; justify-content: space-between;">
              <div class="answers-content" >
                <div class="answers-main-content">
                  {{msg.text_message}}
                </div>
              </div>
              {% if msg.bell_seen  %}
                <p class="newmessagec">
                  <a href="{% url 'chatroom:chatroom' msg.r1uid_id %}">
                    open
                  </a>
                </p>
              {% else %}
                <p class="newmessagec alert-danger">
                <a href="{% url 'chatroom:chatroom' msg.r1uid_id %}">
                  {{msg.r1uid_id|msagecounter:msg.r2uid_id}} new
                </a>
                </p>
              {% endif %}
              <div class="flexer">
                <p class="ft">
                  {{msg.r1uid.hobby}}
                </p>
                <p class="ft">
                  {{msg.text_time | timemodifier}}
                </p>
              </div>
            </div>

          </div>
          </a>
            {% endif %}
        {% endfor %}

</div>
<script>
   // home icon
   const full = document.getElementById('full');
        const ex = document.getElementById('ex');
        const iLinks = document.getElementById('iLinks');

        full.addEventListener('click',function(){
            // full.classList.add('removeIcon');
            full.style.display = 'none';
            // ex.classList.add('showIcon');
            ex.style.display = 'flex';
            iLinks.style.display = 'flex';
        });
        ex.addEventListener('click',function(){
            // full.classList.remove('removeIcon');
            full.style.display = 'flex';
            // ex.classList.remove('showIcon');
            ex.style.display = 'none';
            iLinks.style.display = 'none';
        });

        // end of home icon
</script>
  </body>
</html>

chatroom/templates/chatroom/messages.html
{% load static %}
{% load timemod %}
{% load cloudinary %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <link rel="icon" href="{% static 'questions/images/devcodes.svg' %}" name="favicon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>DevCodes | Messages</title>
    <link rel="stylesheet" href="{% static 'chatroom/messages.css' %}">
    <link rel="stylesheet" href="{% static 'home/icon.css' %}">
  </head>
  <body>
    <div class="nav-bar">
      <!-- Home icon Beginning -->
    <div class="full-icon" id="full">
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
      <div class="row">
          <div class="dot"></div>   <div class="line"></div>
      </div>
  </div>
  <div class="no-padding" id="ex">
      <div class="forward-slash"></div>
      <div class="backward-slash"></div>
  </div>
 <div class="icon-links" id="iLinks">
  <a href="{% url 'home:home' %}" class="Plinks">Home</a>
<a href="{% url 'peers:peers' %}" class="Plinks">Peers</a>
 <a href="{% url 'questions:questions' %}" class="Plinks">Questions
   <i class="fa fa-caret-down"></i></a>
 <a href="{% url 'questions:myquestions' %}" class="Plinks-in">My Questions</a>
  <a href="{% url 'chatroom:inbox' %}" class="Plinks">Inbox <i class="fa fa-envelope"> {{newmessage}}</i>
       </a>
 <a href="{% url 'profile:profile' %}" class="Plinks"> Edit profile </a>
 <a href="{% url 'login:logout' %}" class="Plinks">  Log out </a>
 </div>
  <!-- Ending of icon -->
      <div class="links">
        <a href="{% url 'home:home' %}">Home</a> |
        <a href="{% url 'peers:peers' %}">Peers</a> |
          <!-- dropdowm for questions -->
        <div class="dropdown">
       <div class="dropbtn personalize"> <a href="{% url 'questions:questions' %}">Questions<i class="fa fa-caret-down"></i></a>  </div>
        <div class="dropdown-content">   <a href="{% url 'questions:myquestions' %}">My Questions</a>  </div>
     </div>
        |
        <!-- <a href="{% url 'chatroom:inbox' %}">Inbox</a> -->
        <a href="{% url 'chatroom:inbox' %}">
           Inbox <i class="fa fa-envelope">{{newmessage}}</i>
        </a>
        </div>
        <div class="logoN">
          <img src="{% static 'questions/images/devtitle.svg' %}" class="myimg" alt="logo" style="width:100px; height:50px;">
        </div>
        <div class="user-profile" id="upPart">
          <a> <i class="fa fa-bell">{{notifs}}</i> </a>

             {% cloudinary userdetails.profilepic.url alt=userdetails.username title=userdetails.username className="myimg" height=200 width=100 %}
             <div class="user-dropdown">
               <a href="{% url 'profile:profile' %}">
                 Edit profile
              </a>
              <a href="{% url 'login:logout' %}">
                Log out
              </a>
             </div>
      </div>
  </div>
  <div class="back-icon" style="z-index:3;">
    <a href="{% url 'chatroom:inbox' %}">
      <img src="{% static 'questions/images/back.svg' %}" alt="Back" style="width: 35px; height: 30px;position:fixed;top:10%;z-index:6;">
    </a>
  </div>
    <div class="main">
      <p class="mainuprofile">
        {% cloudinary receiver.profilepic.url className="myimg" alt=receiver.username title=receiver.username height=300 width=200 %}
        <label style="display:block;text-align:center;">{{receiver.username}}</label>
      </p>
      <!-- single message -->
      {% for data in chats %}
        {% if userdetails.uid == data.r1uid_id %}
        <hr>
            <div class="one-message second">
              <div class="message-content">
                {{data.text_message}}
                <p><span class="time">{{data.text_time|timemodifier }}</span></p>
              </div>
              <p class="profile">
                {% cloudinary data.r1uid.profilepic.url className="myimg" alt=data.r1uid.username title=data.r1uid.username height=200 width=100 %}
              </p>
            </div>
      <!-- end of single message -->
        {% else %}
              <hr>
              <!-- other message -->
              <div class="one-message first">
                <p class="profile">
                  {% cloudinary data.r1uid.profilepic.url className="myimg" alt=data.r1uid.username title=data.r1uid.username height=200 width=100 %}
                </p>
                <div class="message-content">
                  {{data.text_message}}
                  <p><span class="second-time">{{data.text_time|timemodifier }}</span></p>
                </div>
              </div>
        <!-- end of single message -->
          {% endif %}
      {% endfor %}
      <!-- end of other message -->
      <!-- start of form -->
      <div class="answers">
        <div class="answer-form">
          <form class="" action="{% url 'chatroom:updatechats' %}" method="post" id="frm">
            {% csrf_token %}
            <!-- <input type="text" name="message"> -->
            <textarea name="msg" rows="3" cols="30" autofocus required maxlength="1024"></textarea>
            <input type="hidden" name="re" value="{{receiver.uid}}">
            <button type="submit" name="submit" value="submit" class="btn btn-info">Send</button>
          </form>
        </div>
      </div>
      <!-- end of form -->
    </div>
    <div class="footer">
    </div>
  </body>
  <script src="{% static 'chatroom/javascript/message.js' %}" charset="utf-8"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>